class TrelloCard:
    def __init__(self, data: dict):
        self.id = data['id']
        self.badges = data['badges']
        self.check_item_states = data['checkItemStates']
        self.closed = data['closed']
        self.due_complete = data['dueComplete']
        self.date_last_activity = data['dateLastActivity']
        self.desc = data['desc']
        self.desc_data = data['descData']
        self.due = data['due']
        self.email = data['email']
        self.id_board = data['idBoard']
        self.id_checklists = data['idChecklists']
        self.id_list = data['idList']
        self.id_members = data['idMembers']
        self.id_members_voted = data['idMembersVoted']
        self.id_short = data['idShort']
        self.id_attachment_cover = data['idAttachmentCover']
        self.labels = data['labels']
        self.id_labels = data['idLabels']
        self.manual_cover_attachment = data['manualCoverAttachment']
        self.name = data['name']
        self.pos = data['pos']
        self.short_link = data['shortLink']
        self.short_url = data['shortUrl']
        self.start = data['start']
        self.subscribed = data['subscribed']
        self.url = data['url']
        self.cover = data['cover']
        self.is_template = data['isTemplate']
        self.card_role = data['cardRole']

    def __repr__(self):
        return f'<Card {self.name} {self.id}>'
